version: '3.5'
services:

  devzone-db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devzone
      - PGDATA=/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
